-- Module: pharmacy
-- Migration 0002: the clinical, stock and compliance tables the boards need.
--
-- Migration 0001 covers the paper trail a pharmacy must keep: who prescribed
-- what, what was dispensed, the controlled substance register and insurance
-- claims. This migration covers the work around it: what a medicine is and how
-- it must be stored, what a patient's clinical record says, what the dispenser
-- checked before handing it over, and the compliance records a regulator or an
-- insurer asks for.
--
-- Conventions are the ones every module follows (see core 0001):
--   * time-ordered UUID version 7 keys, generated by the database,
--   * organization_id on every row, with row level security through prepare_table,
--   * created_at, updated_at, deleted_at and row_version,
--   * money as numeric(18,2), quantities as numeric(18,3),
--   * statuses as text with a check constraint, so a later migration can add a value.
--
-- Nothing in 0001 changes: a migration that has shipped is never edited, so this
-- file only adds.

-- One row per medicine product: what it is, how strong it is, and how it has to
-- be kept. The clinical check screen reads this to warn about a dose, a storage
-- requirement or a missing registration.
create table pharmacy.medicine_details (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  product_id uuid not null references catalog.products (id) on delete cascade,
  -- The regulator's own name for the strength, e.g. "500 mg" or "2 mg/ml".
  generic_name text not null,
  strength_text text not null,
  dosage_form text not null,
  -- e.g. "20 tablets", "100 ml".
  pack_size_text text,
  medicine_schedule text not null default 'general_sale'
    check (medicine_schedule in ('general_sale', 'pharmacy_medicine', 'prescription_only', 'controlled')),
  storage_condition text not null default 'room_temperature'
    check (storage_condition in ('room_temperature', 'refrigerated_two_to_eight')),
  -- Authority registration number, e.g. the Tanzania Medicines and Medical Devices Authority number.
  regulator_registration_number text,
  -- Shelf life a supplier must leave on arrival, in whole months.
  minimum_shelf_life_months_on_delivery integer not null default 0
    check (minimum_shelf_life_months_on_delivery >= 0),
  -- Printed on the label, e.g. "Keep out of reach of children".
  label_warnings text[] not null default '{}',
  is_on_insurance_formulary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1
);
select core.prepare_table('pharmacy.medicine_details');
create unique index medicine_details_product_unique_index
  on pharmacy.medicine_details (organization_id, product_id);
create index medicine_details_generic_name_index
  on pharmacy.medicine_details (organization_id, generic_name);

-- What may be given instead when the prescribed medicine is out of stock.
create table pharmacy.medicine_substitutes (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  product_id uuid not null references catalog.products (id) on delete cascade,
  substitute_product_id uuid not null references catalog.products (id) on delete cascade,
  substitution_kind text not null
    check (substitution_kind in ('same_generic', 'therapeutic')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1,
  check (product_id <> substitute_product_id)
);
select core.prepare_table('pharmacy.medicine_substitutes');
create unique index medicine_substitutes_pair_unique_index
  on pharmacy.medicine_substitutes (organization_id, product_id, substitute_product_id);
create index medicine_substitutes_substitute_index
  on pharmacy.medicine_substitutes (substitute_product_id);

-- What the pharmacy knows about a patient beyond their name and phone number.
-- Kept apart from customers.customers so a clinical field never leaks into a
-- sale, and readable only with pharmacy.clinical_notes.view.
create table pharmacy.patient_clinical_profiles (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  customer_id uuid not null references customers.customers (id) on delete cascade,
  date_of_birth date,
  -- Recorded as the patient states it.
  sex text check (sex in ('female', 'male', 'other', 'unknown')),
  allergies text[] not null default '{}',
  -- Diagnoses read off prescriptions, not asserted by the pharmacist.
  conditions_from_prescriptions text[] not null default '{}',
  insurance_provider_id uuid references pharmacy.insurance_providers (id) on delete set null,
  insurance_member_number text,
  -- Whether the patient agreed to be reminded when a refill is due.
  reminder_consent boolean not null default false,
  reminder_consent_given_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1
);
select core.prepare_table('pharmacy.patient_clinical_profiles');
create unique index patient_clinical_profiles_customer_unique_index
  on pharmacy.patient_clinical_profiles (organization_id, customer_id);
create index patient_clinical_profiles_insurance_index
  on pharmacy.patient_clinical_profiles (insurance_provider_id, insurance_member_number);

-- The pharmacist's own words about a patient or a prescription.
create table pharmacy.clinical_notes (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  customer_id uuid references customers.customers (id) on delete cascade,
  prescription_id uuid references pharmacy.prescriptions (id) on delete cascade,
  note_text text not null,
  written_by_user_id uuid references core.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1,
  check (customer_id is not null or prescription_id is not null)
);
select core.prepare_table('pharmacy.clinical_notes');
create index clinical_notes_customer_index on pharmacy.clinical_notes (customer_id, created_at desc);
create index clinical_notes_prescription_index on pharmacy.clinical_notes (prescription_id);

-- Which two generics must not be given together, and what to say about it.
create table pharmacy.interaction_rules (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  first_generic_name text not null,
  second_generic_name text not null,
  severity text not null
    check (severity in ('information', 'caution', 'serious')),
  message_text text not null,
  -- Where the rule comes from, e.g. the formulary or a clinical guideline.
  source_reference text,
  -- A serious rule is not used until a pharmacist has read it.
  reviewed_by_user_id uuid references core.users (id),
  reviewed_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1,
  check (first_generic_name <> second_generic_name)
);
select core.prepare_table('pharmacy.interaction_rules');
create unique index interaction_rules_pair_unique_index
  on pharmacy.interaction_rules (organization_id, first_generic_name, second_generic_name);
create index interaction_rules_first_index
  on pharmacy.interaction_rules (organization_id, first_generic_name);
create index interaction_rules_second_index
  on pharmacy.interaction_rules (organization_id, second_generic_name);

-- One row per check made on a prescription, so the screen can show what was
-- looked at and what the pharmacist decided.
create table pharmacy.prescription_checks (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  prescription_id uuid not null references pharmacy.prescriptions (id) on delete cascade,
  check_key text not null
    check (check_key in ('identity', 'allergy', 'interaction', 'duplicate_therapy', 'dose_range', 'insurance_cover')),
  result text not null check (result in ('passed', 'warning', 'failed')),
  -- What the check found, in words the pharmacist can read.
  details text,
  checked_by_user_id uuid references core.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1
);
select core.prepare_table('pharmacy.prescription_checks');
create index prescription_checks_prescription_index
  on pharmacy.prescription_checks (prescription_id, created_at desc);
create index prescription_checks_failed_index
  on pharmacy.prescription_checks (organization_id, result) where result <> 'passed';

-- Calling the prescriber back, and what they said.
create table pharmacy.prescriber_contacts (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  prescription_id uuid not null references pharmacy.prescriptions (id) on delete cascade,
  contacted_at timestamptz not null default now(),
  contact_method text not null
    check (contact_method in ('phone', 'text_message', 'email', 'in_person')),
  outcome text not null
    check (outcome in ('prescriber_agreed', 'prescription_changed', 'no_answer')),
  note_text text,
  recorded_by_user_id uuid references core.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1
);
select core.prepare_table('pharmacy.prescriber_contacts');
create index prescriber_contacts_prescription_index
  on pharmacy.prescriber_contacts (prescription_id, contacted_at desc);

-- Every label printed for a dispensed item, including the ones reprinted
-- because the first print was spoiled.
create table pharmacy.dispensing_labels (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  prescription_item_id uuid not null references pharmacy.prescription_items (id) on delete cascade,
  label_text text not null,
  printed_at timestamptz not null default now(),
  printed_by_user_id uuid references core.users (id),
  reprint_count integer not null default 0 check (reprint_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1
);
select core.prepare_table('pharmacy.dispensing_labels');
create index dispensing_labels_item_index
  on pharmacy.dispensing_labels (prescription_item_id, printed_at desc);

-- When a patient's medicine is due again, and whether they agreed to be told.
create table pharmacy.refill_schedules (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  customer_id uuid not null references customers.customers (id) on delete cascade,
  product_id uuid not null references catalog.products (id) on delete cascade,
  -- How long one dispense lasts for this patient, in whole days.
  days_of_supply integer not null check (days_of_supply > 0),
  last_filled_on date,
  next_due_on date,
  reminder_status text not null default 'not_due'
    check (reminder_status in ('not_due', 'scheduled', 'sent', 'no_consent', 'collected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1
);
select core.prepare_table('pharmacy.refill_schedules');
create unique index refill_schedules_customer_product_unique_index
  on pharmacy.refill_schedules (organization_id, customer_id, product_id);
create index refill_schedules_due_index
  on pharmacy.refill_schedules (organization_id, next_due_on)
  where reminder_status in ('not_due', 'scheduled');

-- The fridge, twice a day: what the thermometer read and whether it was in range.
create table pharmacy.temperature_logs (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  branch_id uuid not null references core.branches (id),
  -- Which cold unit, e.g. "Fridge 1".
  storage_unit_name text not null,
  recorded_at timestamptz not null default now(),
  temperature_celsius numeric(5,2) not null,
  is_in_range boolean not null,
  recorded_by_user_id uuid references core.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1
);
select core.prepare_table('pharmacy.temperature_logs');
create index temperature_logs_unit_index
  on pharmacy.temperature_logs (branch_id, storage_unit_name, recorded_at desc);
create index temperature_logs_out_of_range_index
  on pharmacy.temperature_logs (organization_id, recorded_at desc) where not is_in_range;

-- A recall notice from a supplier or the regulator, and what was done about it.
create table pharmacy.recall_notices (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  supplier_name text not null,
  -- The reference on the marketplace recall notice, when it came from there.
  marketplace_recall_reference text,
  product_id uuid not null references catalog.products (id),
  batch_number text not null,
  reason_text text not null,
  -- The class the notice gives the recall.
  recall_class text check (recall_class in ('class_i', 'class_ii', 'class_iii')),
  issued_at date,
  instructions_text text,
  status text not null default 'open'
    check (status in ('open', 'quarantined', 'returned', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1
);
select core.prepare_table('pharmacy.recall_notices');
create index recall_notices_batch_index
  on pharmacy.recall_notices (organization_id, product_id, batch_number);
create index recall_notices_status_index
  on pharmacy.recall_notices (organization_id, status, issued_at desc nulls last);

-- One action taken on a recall: stock quarantined, a patient told, goods sent
-- back, or the supplier's credit note received.
create table pharmacy.recall_actions (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  recall_notice_id uuid not null references pharmacy.recall_notices (id) on delete cascade,
  action_type text not null
    check (action_type in ('quarantined', 'patient_contacted', 'returned_to_supplier', 'credit_received')),
  customer_id uuid references customers.customers (id) on delete set null,
  quantity numeric(18,3),
  done_at timestamptz not null default now(),
  done_by_user_id uuid references core.users (id),
  note_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1
);
select core.prepare_table('pharmacy.recall_actions');
create index recall_actions_notice_index
  on pharmacy.recall_actions (recall_notice_id, done_at desc);
create index recall_actions_customer_index on pharmacy.recall_actions (customer_id);

-- The licences a branch must hold and show: premises, pharmacist registration,
-- business licence, controlled drugs permit, fire certificate and the fridge's
-- calibration certificate.
create table pharmacy.licence_documents (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  branch_id uuid not null references core.branches (id),
  licence_type text not null
    check (licence_type in (
      'premises', 'pharmacist_registration', 'business', 'controlled_permit',
      'fire_certificate', 'fridge_calibration'
    )),
  holder_name text not null,
  licence_number text not null,
  issued_on date,
  expires_on date,
  -- The scan or photo, stored as a core attachment.
  attachment_id uuid references core.attachments (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1
);
select core.prepare_table('pharmacy.licence_documents');
create unique index licence_documents_number_unique_index
  on pharmacy.licence_documents (organization_id, licence_number);
create index licence_documents_expiring_index
  on pharmacy.licence_documents (branch_id, expires_on)
  where expires_on is not null and deleted_at is null;

-- What was checked when a delivery arrived: expiry dates, packaging, cold chain
-- and quantity. A cold chain check keeps the temperatures that were measured.
create table pharmacy.receipt_quality_checks (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  goods_receipt_line_id uuid not null references purchasing.goods_receipt_lines (id) on delete cascade,
  check_key text not null
    check (check_key in ('expiry', 'packaging', 'cold_chain', 'quantity')),
  result text not null check (result in ('passed', 'warning', 'failed')),
  minimum_temperature_celsius numeric(5,2),
  maximum_temperature_celsius numeric(5,2),
  note_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1
);
select core.prepare_table('pharmacy.receipt_quality_checks');
create index receipt_quality_checks_line_index
  on pharmacy.receipt_quality_checks (goods_receipt_line_id, created_at desc);
create index receipt_quality_checks_failed_index
  on pharmacy.receipt_quality_checks (organization_id, created_at desc) where result <> 'passed';

-- Claims are submitted to an insurer in batches, not one at a time: one period,
-- one provider, one total.
create table pharmacy.insurance_claim_batches (
  id uuid primary key default core.generate_uuid_v7(),
  organization_id uuid not null references core.organizations (id) on delete cascade,
  insurance_provider_id uuid not null references pharmacy.insurance_providers (id),
  period_start_on date not null,
  period_end_on date not null,
  status text not null default 'open'
    check (status in ('open', 'submitted', 'queried', 'paid')),
  submitted_at timestamptz,
  claimed_amount numeric(18,2) not null default 0 check (claimed_amount >= 0),
  paid_amount numeric(18,2) not null default 0 check (paid_amount >= 0),
  -- What the insurer said does not qualify.
  deducted_amount numeric(18,2) not null default 0 check (deducted_amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  row_version bigint not null default 1,
  check (period_end_on >= period_start_on)
);
select core.prepare_table('pharmacy.insurance_claim_batches');
create index insurance_claim_batches_provider_index
  on pharmacy.insurance_claim_batches (insurance_provider_id, period_start_on desc);

-- A claim belongs to the batch it was submitted in.
alter table pharmacy.insurance_claims
  add column claim_batch_id uuid references pharmacy.insurance_claim_batches (id) on delete set null;
create index insurance_claims_batch_index on pharmacy.insurance_claims (claim_batch_id);