//! The dashboard's styles, from `PharmacyDashboard`.
//!
//! Every colour here is a theme token, so the board is legible in the light and
//! the dark appearance without a second table.

use rok_ui::prelude::*;

styles! {
    pub DASHBOARD = {
        root: { display: flex, flex_direction: column, gap: 4 },
        row: { display: flex, flex_direction: row, gap: 4, align: stretch },
        tiles: { display: flex, flex_direction: row, gap: 3 },
        tile: {
            grow: 1,
            basis: 0,
            min_width: 0,
            display: flex,
            flex_direction: column,
            gap: 1,
            padding: 4,
            background: card,
            border: 1,
            border_color: border,
            cursor: pointer,
            hover: { border_color: input },
        },
        tile_label: { text: {13.}, color: muted_foreground },
        tile_value: { font_family: mono, text: {26.}, font: bold },
        small: { text: {12.}, color: muted_foreground },
        meta: { text: {13.}, color: muted_foreground },
        card: {
            basis: 0,
            min_width: 0,
            display: flex,
            flex_direction: column,
            gap: 2,
            padding: 4.5,
            background: card,
            border: 1,
            border_color: border,
        },
        card_head: { display: flex, flex_direction: row, justify: between, align: center },
        card_title: { text: {16.}, font: semibold },
        task: {
            display: flex,
            flex_direction: row,
            align: center,
            gap: 3,
            min_height: 13,
            padding_y: 2,
            padding_x: 2.5,
            border_top: 1,
            border_color: muted,
            cursor: pointer,
            hover: { background: background },
        },
        task_chip: {
            width: 23,
            shrink: 0,
            padding_y: {px(3.)},
            text: {12.},
            font: semibold,
            text_align: center,
        },
        task_text: { display: flex, flex_direction: column, grow: 1, min_width: 0 },
        task_title: { font: semibold },
        task_action: { shrink: 0, text: {13.}, font: semibold },
        bars: {
            display: flex,
            flex_direction: row,
            align: end,
            gap: 2.5,
            height: {px(150.)},
            padding_bottom: 1,
            border_bottom: 1,
            border_color: border,
        },
        bar_column: {
            grow: 1,
            basis: 0,
            display: flex,
            flex_direction: column,
            align: center,
            justify: end,
            gap: 1,
            height: full,
        },
        bar_figure: { font_family: mono, text: {11.}, color: muted_foreground },
        hour_labels: { display: flex, flex_direction: row, gap: 2.5 },
        hour_label: {
            grow: 1,
            basis: 0,
            text_align: center,
            font_family: mono,
            text: {12.},
            color: muted_foreground,
        },
        table_head: {
            display: flex,
            flex_direction: row,
            padding_y: 1,
            text: {12.},
            font: semibold,
            color: muted_foreground,
        },
        table_row: { display: flex, flex_direction: row, padding_y: {px(7.)}, border_top: 1, border_color: muted },
        first_column: { grow: 1, min_width: 0, truncate: true },
        number_column: { width: 20, shrink: 0, text_align: right, font_family: mono },
        number_head: { width: 20, shrink: 0, text_align: right },
        split: { display: flex, flex_direction: row, height: 3.5 },
        legend: { display: flex, flex_direction: row, align: center, gap: 2.5 },
        dot: { size: 2.5, shrink: 0, radius: full },
        legend_amount: { width: 21, text_align: right, font_family: mono, font: semibold },
        link: { text: {13.}, font: semibold, color: primary, cursor: pointer },
        notice: {
            display: flex,
            flex_direction: column,
            gap: 2,
            padding: 6,
            background: card,
            border: 1,
            border_color: border,
        },
        notice_title: { font: semibold },
        notice_body: { text: {13.}, color: muted_foreground },
    }
}
